# harness/render_reaper_slot.rb — render ONE owner-designed slot through the
# live Reaper bridge, import only that fresh revision, then rebuild the listen
# track (M4b interactive loop).
#
# Why one slot: partial replacement is expected. An all-regions render would
# accidentally turn untouched disposable-ReaSynth slots into pinned stems.
#
# Owner-document law: every render gets a fresh, never-overwritten directory:
# data/audio_listen/inbox/runs/<timestamp>-<slot>/<slot>.wav. The importer is
# given that exact source and never deletes/moves it. Repeat iterations create
# new revisions instead of overwriting prior inbox audio.
#
# Usage:
#   ruby -Isrc -Iharness harness/render_reaper_slot.rb <slot>
#   ruby -Isrc -Iharness harness/render_reaper_slot.rb <slot> --verify-only
#
# verify-only proves real Reaper render format/duration without touching the
# production manifest or stems (used for disposable scaffold verification).

require "json"
require "digest"
require "fileutils"
require "rbconfig"
require_relative "reaper_bridge"
require_relative "import_stems"

REPO = File.expand_path("..", __dir__)
LISTEN_DIR = File.join(REPO, "data/audio_listen")
OWNER_PROJECT = File.join(LISTEN_DIR, "reaper/owner_project.rpp")
INBOX_DIR = File.join(LISTEN_DIR, "inbox")
SLOT_SPACING_S = 10.0

slot = ARGV[0] or abort "usage: render_reaper_slot.rb <slot> [--verify-only]"
verify_only = ARGV.include?("--verify-only")
slots = JSON.parse(File.read(File.join(LISTEN_DIR, "fixtures.json"))).fetch("tones")
spec = slots[slot] or abort "unknown slot #{slot.inspect}; valid: #{slots.keys.join(', ')}"
index = slots.keys.index(slot)
start_s = index * SLOT_SPACING_S
end_s = start_s + spec.fetch("dur_s")

B = GTA::ReaperBridge
B.assert_alive!
info = B.call!("project_get_info")
normalize = ->(p) { File.expand_path(p.to_s).tr("\\", "/").downcase }
abort "REFUSED: active REAPER project is #{info['file_path'].inspect}, not owner_project.rpp" unless normalize.call(info["file_path"]) == normalize.call(OWNER_PROJECT)
tracks = B.call!("track_get_all").fetch("tracks")
actual_track = tracks.find { |t| t["index"] == index }
abort "REFUSED: track #{index} is #{actual_track&.dig('name').inspect}, expected #{slot.inspect}" unless actual_track&.dig("name") == slot

stamp = Time.now.strftime("%Y%m%d-%H%M%S")
run_dir = File.join(INBOX_DIR, "runs", "#{stamp}-#{Process.pid}-#{slot}")
FileUtils.mkdir_p(run_dir)
target = File.join(run_dir, "#{slot}.wav")
abort "REFUSED: render target already exists: #{target}" if File.exist?(target)

# Persist the owner's latest plugin/patch edits before rendering.
B.call!("project_save")

script_path = File.join(B.scripts_dir, "gta_render_one_slot.lua")
set_script = <<~LUA
  -- Generated by game-two-audio/render_reaper_slot.rb.
  local p = 0
  reaper.GetSetProjectInfo_String(p, "RENDER_FILE", [[#{run_dir.tr('\\', '/')}]], true)
  reaper.GetSetProjectInfo_String(p, "RENDER_PATTERN", [[#{slot}]], true)
  reaper.GetSetProjectInfo(p, "RENDER_SRATE", 48000, true)
  reaper.GetSetProjectInfo(p, "RENDER_CHANNELS", 1, true)
  reaper.GetSetProjectInfo(p, "RENDER_BOUNDSFLAG", 0, true) -- custom bounds
  reaper.GetSetProjectInfo(p, "RENDER_STARTPOS", #{start_s}, true)
  reaper.GetSetProjectInfo(p, "RENDER_ENDPOS", #{end_s}, true)
  reaper.GetSetProjectInfo(p, "RENDER_SETTINGS", 0, true)   -- master mix
  reaper.GetSetProjectInfo(p, "RENDER_TAILFLAG", 0, true)
  reaper.GetSetProjectInfo(p, "RENDER_TAILMS", 0, true)
  local out = select(2, reaper.GetSetProjectInfo_String(p, "RENDER_FILE", "", false))
  local pat = select(2, reaper.GetSetProjectInfo_String(p, "RENDER_PATTERN", "", false))
  local result = string.format("dir=%s|pattern=%s|bounds=%d|start=%.6f|end=%.6f|sr=%d|ch=%d|tail=%d",
    out, pat,
    reaper.GetSetProjectInfo(p, "RENDER_BOUNDSFLAG", 0, false),
    reaper.GetSetProjectInfo(p, "RENDER_STARTPOS", 0, false),
    reaper.GetSetProjectInfo(p, "RENDER_ENDPOS", 0, false),
    reaper.GetSetProjectInfo(p, "RENDER_SRATE", 0, false),
    reaper.GetSetProjectInfo(p, "RENDER_CHANNELS", 0, false),
    reaper.GetSetProjectInfo(p, "RENDER_TAILFLAG", 0, false))
  reaper.SetExtState("reaper_mcp_script_result", "last_result", result, false)
LUA
restore_script = <<~LUA
  -- Restore canonical all-regions settings after one-slot render.
  local p = 0
  reaper.GetSetProjectInfo_String(p, "RENDER_FILE", [[#{INBOX_DIR.tr('\\', '/')}]], true)
  reaper.GetSetProjectInfo_String(p, "RENDER_PATTERN", "$region", true)
  reaper.GetSetProjectInfo(p, "RENDER_SRATE", 48000, true)
  reaper.GetSetProjectInfo(p, "RENDER_CHANNELS", 1, true)
  reaper.GetSetProjectInfo(p, "RENDER_BOUNDSFLAG", 3, true)
  reaper.GetSetProjectInfo(p, "RENDER_SETTINGS", 0, true)
  reaper.GetSetProjectInfo(p, "RENDER_TAILFLAG", 0, true)
  reaper.GetSetProjectInfo(p, "RENDER_TAILMS", 0, true)
  reaper.SetExtState("reaper_mcp_script_result", "last_result", "restored all-regions render settings", false)
LUA

begin
  File.write(script_path, set_script)
  puts "reaper:render #{slot} — config read-back: #{B.run_script!('gta_render_one_slot.lua')}"
  B.call!("project_export_audio", {}, timeout: 600)
ensure
  # Best effort even when render fails: leave owner_project in its canonical
  # all-regions configuration rather than a hidden one-slot state.
  begin
    File.write(script_path, restore_script)
    puts "reaper:render #{slot} — #{B.run_script!('gta_render_one_slot.lua')}"
    B.call!("project_save")
  rescue GTA::ReaperBridge::BridgeError => e
    warn "WARNING: could not restore canonical render settings: #{e.message}"
  end
end

abort "RENDER FAILED: expected #{target}, got #{Dir[File.join(run_dir, '*')].map { |p| File.basename(p) }.inspect}" unless File.exist?(target)
w = GTA::StemImport.read_wav(target)
frames = w[:data].bytesize / (w[:channels] * w[:bits] / 8)
expected = (spec.fetch("dur_s") * 48_000).round
puts "reaper:render #{slot} — real WAV: tag=#{w[:tag]} #{w[:bits]}-bit #{w[:channels]}ch @#{w[:sample_rate]} Hz, #{frames} frames (expected #{expected})"
abort "RENDER FAILED: sample rate #{w[:sample_rate]}, expected 48000" unless w[:sample_rate] == 48_000
abort "RENDER FAILED: frame count #{frames}, expected #{expected}" unless frames == expected

if verify_only
  puts "reaper:render #{slot} — VERIFY-ONLY PASS; manifest/stems untouched; revision retained at #{target}"
  exit 0
end

old_shas = Dir[File.join(REPO, "tmp/listen/*.wav")].to_h do |p|
  [File.basename(p), Digest::SHA256.file(p).hexdigest]
end
result = GTA::StemImport.run!(LISTEN_DIR, only_slots: [slot], sources: { slot => target })
abort "IMPORT FAILED: #{result[:refused].inspect}" unless result[:refused].empty? && result[:accepted] == [slot]

replays = Dir[File.join(REPO, "harness/replays/*.json")].sort
Dir.chdir(REPO) do
  ok = system(RbConfig.ruby, "-Isrc", "-Iharness", "harness/run_listen.rb", *replays)
  abort "LISTEN FAILED after importing #{slot}" unless ok
end
new_shas = Dir[File.join(REPO, "tmp/listen/*.wav")].to_h do |p|
  [File.basename(p), Digest::SHA256.file(p).hexdigest]
end
puts "reaper:render #{slot} — listen sha provenance:"
new_shas.sort.each do |name, sha|
  old = old_shas[name]
  change = old.nil? ? "first render -> #{sha[0, 8]}" :
           old == sha ? "#{sha[0, 8]} unchanged" : "#{old[0, 8]} -> #{sha[0, 8]}"
  puts "  #{name}: #{change}"
end
puts "reaper:render #{slot} — IMPORTED. Play tmp/listen/*.wav; inbox revision retained."
